name: CI

on: 
  push:
    branches: [auto_ci]
  pull_request:
    branches: [auto_ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Upload Test Reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/test-results/test/**

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: irisliong04
          password: 1R1Sg00d**

      - name: Build Docker image
        run: docker build -t irisliong04/auto_ci:latest .

      - name: Push Docker Image
        run: docker push irisliong04/auto_ci:latest